@{
	RootModule = 'WinCloudInit.psm1'
	ModuleVersion = '1.0.0'
	GUID = '5f24b005-82e2-4d16-8470-51c1851f5562'
	Author = 'Alexey Miasoedov'
	CompanyName = 'Intermedia'
	Copyright = '(c) 2016 Alexey Miasoedov. All rights reserved.'
	Description = 'CloudInit module for Windows'
	PowerShellVersion = '4.0'
	FunctionsToExport = 'Set-WinCloudInit','Start-WinCloudInit'
	CmdletsToExport = '*'
	VariablesToExport = '*'
	AliasesToExport = '*'
	FileList = 'WinCloudInit.psm1'
}